### ISSUE TITLE
Charging options -- enterprise customers for RECAP Search Alerts

### ISSUE THREAD

**Issue by s-taube** [freelawproject/foresight#54]
We want to charge enterprise users on a per-usage basis.
What are different per-usage charging options?

Notes:

- OpenAI sends people to external payment page at the end of process
- check out Stripe

**Definition of Done:**
- A list of different charging options
- Pros and cons of each

**Comment by s-taube** [comment]
Per Mike (via slack)...

A few options:

One way is we hash out a deal with an org, and bill them by hand at the end of each month according to whatever rate we agreed to. AWS does infinite billing, and it's mostly fine. You can set alerts to stay informed.

    Pro:
      No code

    Con:
        Monthly work. 
        No cap on the amount we may ask for next month.

Or....we ask for payment up front and then that's in their bank and we re-up when it gets low, OpenAI/Anthropic style.

      Pro:
         Regular, controlled re-ups
         Customer manages budget
         Automatic payments, in advance of usage

     Con:
        Code, lots of code
         If it zero's, alerts get missed

**Comment by mlissner** [comment]
I have to say, I like the re-ups, but I think the simplicity of the per-use with alerts is a big benefit.

**Comment by s-taube** [comment]
I should have added -- the above comment is something you shared in slack. I'm trying to get everything in all in one place!

**Comment by s-taube** [comment]
Added options [here](https://docs.google.com/document/d/1mu5K8RbihPoSFVH-p9vLvH6F81mnxmzDIsQ5Zqfmmvg/edit?tab=t.0).

**Comment by mlissner** [comment]
Nice. Let's chat tomorrow!
